bugfix: Error when Required information is not satisfied
 File "soothsayer\app\infrastructure\repositoriesImpl.py", line 102, in <listcomp>
    "required_info": state.required_info.model_dump(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model_dump'